jobs:
  register:
    name: Package, Publish, and Register
    runs-on:
    - ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      # PACKAGE AND BUILD STEPS
      - id: register
        uses: docker://ghcr.io/buildpacks/actions/registry/request-add-entry:5.1.0
        with:
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          id: ${{ steps.package.outputs.bp_id }}
          version: ${{ steps.package.outputs.version }}
          address: ${{ steps.package.outputs.address }}
