name: UCPD-Scrape
on:
  schedule:
    - cron: "0 0 16 ? * MON,TUE,WED,THU,FRI,SAT *"

jobs:
  scrape:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.6.5
          python-version: 3.11

      - name: Scrape the UCPD Site
        run: uv run python -m incident_scraper update
